version: '3'

services:
  jenkins:
    image: jenkins-go
    ports:
      - "8091:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_portal_db
    ports:
      - "3307:3306"

volumes:
  jenkins_home:
