version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  app:
    image: sivanandhini23/db_gorm_app:latest
    container_name: gorm_app_container
    ports:
      - "9091:8080"
    depends_on:
      - db
    volumes:
      - ./config:/root/Config
