// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/job.proto

package pb_file

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecruiterId    int32                  `protobuf:"varint,1,opt,name=recruiter_id,json=recruiterId,proto3" json:"recruiter_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	SkillsRequired string                 `protobuf:"bytes,4,opt,name=skills_required,json=skillsRequired,proto3" json:"skills_required,omitempty"`
	Location       string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Salary         float64                `protobuf:"fixed64,6,opt,name=salary,proto3" json:"salary,omitempty"`
	JobType        string                 `protobuf:"bytes,7,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetRecruiterId() int32 {
	if x != nil {
		return x.RecruiterId
	}
	return 0
}

func (x *JobRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *JobRequest) GetSkillsRequired() string {
	if x != nil {
		return x.SkillsRequired
	}
	return ""
}

func (x *JobRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *JobRequest) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *JobRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_proto_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobID) Reset() {
	*x = JobID{}
	mi := &file_proto_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobID) ProtoMessage() {}

func (x *JobID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobID.ProtoReflect.Descriptor instead.
func (*JobID) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{2}
}

func (x *JobID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BatchJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobRequest          `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchJobRequest) Reset() {
	*x = BatchJobRequest{}
	mi := &file_proto_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchJobRequest) ProtoMessage() {}

func (x *BatchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchJobRequest.ProtoReflect.Descriptor instead.
func (*BatchJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{3}
}

func (x *BatchJobRequest) GetJobs() []*JobRequest {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type BatchJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchJobResponse) Reset() {
	*x = BatchJobResponse{}
	mi := &file_proto_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchJobResponse) ProtoMessage() {}

func (x *BatchJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchJobResponse.ProtoReflect.Descriptor instead.
func (*BatchJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{4}
}

func (x *BatchJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchJobResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_proto_job_proto protoreflect.FileDescriptor

const file_proto_job_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/job.proto\x1a\x1cgoogle/api/annotations.proto\"\xdf\x01\n" +
	"\n" +
	"JobRequest\x12!\n" +
	"\frecruiter_id\x18\x01 \x01(\x05R\vrecruiterId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fskills_required\x18\x04 \x01(\tR\x0eskillsRequired\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x16\n" +
	"\x06salary\x18\x06 \x01(\x01R\x06salary\x12\x19\n" +
	"\bjob_type\x18\a \x01(\tR\ajobType\"'\n" +
	"\vJobResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x17\n" +
	"\x05JobID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"2\n" +
	"\x0fBatchJobRequest\x12\x1f\n" +
	"\x04jobs\x18\x01 \x03(\v2\v.JobRequestR\x04jobs\"D\n" +
	"\x10BatchJobResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors2\xfa\x01\n" +
	"\n" +
	"JobService\x128\n" +
	"\tCreateJob\x12\v.JobRequest\x1a\f.JobResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/jobs\x12I\n" +
	"\n" +
	"CreateJobs\x12\x10.BatchJobRequest\x1a\x11.BatchJobResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/jobs/batch\x121\n" +
	"\x06GetJob\x12\x06.JobID\x1a\v.JobRequest\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/jobs/{id}\x124\n" +
	"\bDeletJob\x12\x06.JobID\x1a\f.JobResponse\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/jobs/{id}B\vZ\t./pb_fileb\x06proto3"

var (
	file_proto_job_proto_rawDescOnce sync.Once
	file_proto_job_proto_rawDescData []byte
)

func file_proto_job_proto_rawDescGZIP() []byte {
	file_proto_job_proto_rawDescOnce.Do(func() {
		file_proto_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_job_proto_rawDesc), len(file_proto_job_proto_rawDesc)))
	})
	return file_proto_job_proto_rawDescData
}

var file_proto_job_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_job_proto_goTypes = []any{
	(*JobRequest)(nil),       // 0: JobRequest
	(*JobResponse)(nil),      // 1: JobResponse
	(*JobID)(nil),            // 2: JobID
	(*BatchJobRequest)(nil),  // 3: BatchJobRequest
	(*BatchJobResponse)(nil), // 4: BatchJobResponse
}
var file_proto_job_proto_depIdxs = []int32{
	0, // 0: BatchJobRequest.jobs:type_name -> JobRequest
	0, // 1: JobService.CreateJob:input_type -> JobRequest
	3, // 2: JobService.CreateJobs:input_type -> BatchJobRequest
	2, // 3: JobService.GetJob:input_type -> JobID
	2, // 4: JobService.DeletJob:input_type -> JobID
	1, // 5: JobService.CreateJob:output_type -> JobResponse
	4, // 6: JobService.CreateJobs:output_type -> BatchJobResponse
	0, // 7: JobService.GetJob:output_type -> JobRequest
	1, // 8: JobService.DeletJob:output_type -> JobResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_job_proto_init() }
func file_proto_job_proto_init() {
	if File_proto_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_job_proto_rawDesc), len(file_proto_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_job_proto_goTypes,
		DependencyIndexes: file_proto_job_proto_depIdxs,
		MessageInfos:      file_proto_job_proto_msgTypes,
	}.Build()
	File_proto_job_proto = out.File
	file_proto_job_proto_goTypes = nil
	file_proto_job_proto_depIdxs = nil
}
