// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/user.proto

package pb_file

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contact         string                 `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	Skills          string                 `protobuf:"bytes,3,opt,name=skills,proto3" json:"skills,omitempty"`
	Age             int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	ExperienceYears int32                  `protobuf:"varint,5,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	Education       string                 `protobuf:"bytes,6,opt,name=education,proto3" json:"education,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *UserRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *UserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserRequest) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *UserRequest) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserID) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Contact         string                 `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	Skills          string                 `protobuf:"bytes,3,opt,name=skills,proto3" json:"skills,omitempty"`
	Age             int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	ExperienceYears int32                  `protobuf:"varint,5,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	Education       string                 `protobuf:"bytes,6,opt,name=education,proto3" json:"education,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetResponse) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *GetResponse) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *GetResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GetResponse) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *GetResponse) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GetResponse         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetUsers() []*GetResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Contact         string                 `protobuf:"bytes,3,opt,name=contact,proto3" json:"contact,omitempty"`
	Skills          string                 `protobuf:"bytes,4,opt,name=skills,proto3" json:"skills,omitempty"`
	Age             int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	ExperienceYears int32                  `protobuf:"varint,6,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	Education       string                 `protobuf:"bytes,7,opt,name=education,proto3" json:"education,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *UpdateRequest) GetSkills() string {
	if x != nil {
		return x.Skills
	}
	return ""
}

func (x *UpdateRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateRequest) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *UpdateRequest) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x1a\x1cgoogle/api/annotations.proto\"\xae\x01\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontact\x18\x02 \x01(\tR\acontact\x12\x16\n" +
	"\x06skills\x18\x03 \x01(\tR\x06skills\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12)\n" +
	"\x10experience_years\x18\x05 \x01(\x05R\x0fexperienceYears\x12\x1c\n" +
	"\teducation\x18\x06 \x01(\tR\teducation\"(\n" +
	"\fUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xae\x01\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontact\x18\x02 \x01(\tR\acontact\x12\x16\n" +
	"\x06skills\x18\x03 \x01(\tR\x06skills\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12)\n" +
	"\x10experience_years\x18\x05 \x01(\x05R\x0fexperienceYears\x12\x1c\n" +
	"\teducation\x18\x06 \x01(\tR\teducation\"\a\n" +
	"\x05Empty\"2\n" +
	"\fListResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.GetResponseR\x05users\"\xc0\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontact\x18\x03 \x01(\tR\acontact\x12\x16\n" +
	"\x06skills\x18\x04 \x01(\tR\x06skills\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12)\n" +
	"\x10experience_years\x18\x06 \x01(\x05R\x0fexperienceYears\x12\x1c\n" +
	"\teducation\x18\a \x01(\tR\teducation2\xb5\x02\n" +
	"\vuserservice\x12<\n" +
	"\n" +
	"CreateUser\x12\f.UserRequest\x1a\r.UserResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/users\x125\n" +
	"\aGetUser\x12\a.UserID\x1a\f.GetResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/users/{id}\x121\n" +
	"\bListUser\x12\x06.Empty\x1a\r.ListResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/users\x129\n" +
	"\n" +
	"DeleteUser\x12\a.UserID\x1a\r.UserResponse\"\x13\x82\xd3\xe4\x93\x02\r*\v/users/{id}\x12C\n" +
	"\n" +
	"UpdateUser\x12\x0e.UpdateRequest\x1a\r.UserResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/users/{id}B\vZ\t./pb_fileb\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_user_proto_goTypes = []any{
	(*UserRequest)(nil),   // 0: UserRequest
	(*UserResponse)(nil),  // 1: UserResponse
	(*UserID)(nil),        // 2: UserID
	(*GetResponse)(nil),   // 3: GetResponse
	(*Empty)(nil),         // 4: Empty
	(*ListResponse)(nil),  // 5: ListResponse
	(*UpdateRequest)(nil), // 6: UpdateRequest
}
var file_proto_user_proto_depIdxs = []int32{
	3, // 0: ListResponse.users:type_name -> GetResponse
	0, // 1: userservice.CreateUser:input_type -> UserRequest
	2, // 2: userservice.GetUser:input_type -> UserID
	4, // 3: userservice.ListUser:input_type -> Empty
	2, // 4: userservice.DeleteUser:input_type -> UserID
	6, // 5: userservice.UpdateUser:input_type -> UpdateRequest
	1, // 6: userservice.CreateUser:output_type -> UserResponse
	3, // 7: userservice.GetUser:output_type -> GetResponse
	5, // 8: userservice.ListUser:output_type -> ListResponse
	1, // 9: userservice.DeleteUser:output_type -> UserResponse
	1, // 10: userservice.UpdateUser:output_type -> UserResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
