# prod:
#   username: "test"
#   password: "pass"
#   db_host: "127.0.0.1"
#   db_port: 3306
#   # db_name: "job_portal_db"

prod:
  db_host: host.docker.internal   # change later to compose service name “db”
  db_port: 3306
  username: "test"
  password: "pass"
  db_name: "job_portal_db"

