# prod:
#   username: "test"
#   password: "pass"
#   db_host: "127.0.0.1"
#   db_port: 3306
#   # db_name: "job_portal_db"

prod:
  host: db                # 👈 This matches the service name in docker-compose.yml
  port: 3306
  username: myuser
  password: mypassword
  dbname: mydb
  db_port: 3306

